"""Все ORM-модели. Импортируются здесь для Alembic autogenerate."""

from app.db.base import Base
from app.models.car import (
    BodyType,
    CarBody,
    CarBrand,
    CarConfiguration,
    CarEngine,
    CarGeneration,
    CarModel,
    CarTrim,
    DriveType,
    FuelType,
    TransmissionType,
)
from app.models.content import (
    Comment,
    CommentStatus,
    Component,
    ComponentCategory,
    ComponentPosition,
    ContentStatus,
    DiagnosticCheck,
    DiagnosticRule,
    Difficulty,
    Guide,
    GuideConfiguration,
    GuideMedia,
    GuidePrecaution,
    GuideStep,
    MediaType,
    Model3D,
    Model3DPart,
    StepCheck,
    StepConsumable,
    StepTool,
    StepVariation,
    StepWarning,
    SubscriptionPlan,
    Symptom,
    SymptomCategory,
    TechSpec,
    TechSpecCategory,
    UserSubscription,
    WarningSeverity,
    WarningType,
)
from app.models.user import RefreshToken, User, UserCar, UserRole

__all__ = [
    "Base",
    # Car
    "CarBrand",
    "CarModel",
    "CarGeneration",
    "CarEngine",
    "CarBody",
    "CarTrim",
    "CarConfiguration",
    "FuelType",
    "TransmissionType",
    "DriveType",
    "BodyType",
    # User
    "User",
    "UserCar",
    "UserRole",
    "RefreshToken",
    # Content
    "ComponentCategory",
    "Component",
    "ComponentPosition",
    "Guide",
    "GuideConfiguration",
    "GuidePrecaution",
    "GuideMedia",
    "GuideStep",
    "StepTool",
    "StepConsumable",
    "StepWarning",
    "StepVariation",
    "StepCheck",
    "Comment",
    "TechSpecCategory",
    "TechSpec",
    "SymptomCategory",
    "Symptom",
    "DiagnosticRule",
    "DiagnosticCheck",
    "Model3D",
    "Model3DPart",
    "SubscriptionPlan",
    "UserSubscription",
    # Enums
    "Difficulty",
    "ContentStatus",
    "CommentStatus",
    "WarningSeverity",
    "WarningType",
    "MediaType",
]
